//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusFormWithUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perpustakaanEntities239 : DbContext
    {
        public perpustakaanEntities239()
            : base("name=perpustakaanEntities239")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tabel_buku> tabel_buku { get; set; }
        public virtual DbSet<tabel_pegawai> tabel_pegawai { get; set; }
        public virtual DbSet<tabel_peminjam> tabel_peminjam { get; set; }
        public virtual DbSet<tabel_pengembalian> tabel_pengembalian { get; set; }
        public virtual DbSet<tabel_transaksi_peminjaman> tabel_transaksi_peminjaman { get; set; }
    }
}
