//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusFormWithUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel_pengembalian
    {
        public int id_pengembalian { get; set; }
        public int id_peminjaman { get; set; }
        public System.DateTime tanggal_kembali { get; set; }
        public Nullable<int> denda { get; set; }
    
        public virtual tabel_transaksi_peminjaman tabel_transaksi_peminjaman { get; set; }
    }
}
