//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusFormWithUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel_buku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabel_buku()
        {
            this.tabel_transaksi_peminjaman = new HashSet<tabel_transaksi_peminjaman>();
        }
    
        public int id_buku { get; set; }
        public string nama_buku { get; set; }
        public string penerbit_buku { get; set; }
        public int stok_buku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabel_transaksi_peminjaman> tabel_transaksi_peminjaman { get; set; }
    }
}
