//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusFormWithUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel_transaksi_peminjaman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabel_transaksi_peminjaman()
        {
            this.tabel_pengembalian = new HashSet<tabel_pengembalian>();
        }
    
        public int id_peminjaman { get; set; }
        public int id_peminjam { get; set; }
        public int id_pegawai { get; set; }
        public int id_buku { get; set; }
        public System.DateTime tanggal_peminjaman { get; set; }
        public System.DateTime tanggal_harus_kembali { get; set; }
        public int status { get; set; }
    
        public virtual tabel_buku tabel_buku { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabel_pengembalian> tabel_pengembalian { get; set; }
    }
}
