//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerpusFormWithUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel_peminjam
    {
        public int id_peminjam { get; set; }
        public string nama_peminjam { get; set; }
        public string alamat_peminjam { get; set; }
        public string password_peminjam { get; set; }
    }
}
